# Print-error
Instead of the whole process getting terminated due to an error, you can now continue the process with the help of the Try-catch method that I used in this program. 
